export const REACT_APP_SUPABASE_URL = "https://mgqwxjrduhaqmjjavswp.supabase.co";
export const REACT_APP_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ncXd4anJkdWhhcW1qamF2c3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTg3NjUwNjMsImV4cCI6MjAxNDM0MTA2M30.6GElTuc0Pf-dx4b-60UO6LbIvm6cfopAvjrkhdk06Dc";
